name: Update_Rules
on:
  # push:
  #  branches: 
  #    - master
  schedule:
    - cron: 0 0 * * *
  # release:
  #   types: [published]
  watch:
    types: started
    
jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      
      - name: update
        run: |
          chmod 0755 ./update.sh
          ./update.sh
      
      - name: Push Commits
        run : |
          git config --global user.email "ycg31@qq.com"
          git config --global user.name "ycg31"
          git add . || echo "1"
          git commit -m "github_actions" -a;
          git push "https://ycg31:$GITHUB_TOKEN@github.com/ycg31/KoolProxy.git" master
      

      
      - name: upload to gitee 传到码云
        run: |
          git config --global user.email "ycg31@qq.com"
          git config --global user.name "ycg31"
          git clone --depth 1 https://ycg31:${{ secrets.GITEE_TOKEN }}@gitee.com/ycg31/KoolProxy gitee
          mkdir -p gitee/rules/
          cp -rf ./rules/ gitee/
          cp -rf ./tmp/koolproxy.log gitee/
          cd gitee
          git add . || echo "1"
          git commit -m "github_actions" -a;
          git push || (sleep 30m && git push) || (sleep 30m && git push)
      
      - name: upload to CODING 传到CODING
        run: |
          git config --global user.email "ycg31@qq.com"
          git config --global user.name "TzePUfjoaA"
          git clone --depth 1 https://TzePUfjoaA:${{ secrets.CODING_TOKEN }}@e.coding.net/ycg31/KoolProxy coding
          mkdir -p coding/rules/
          cp -rf ./rules/ coding/
          cp -rf ./tmp/koolproxy.log coding/
          cd coding
          git add . || echo "1"
          git commit -m "github_actions" -a;
          git push || (sleep 30m && git push) || (sleep 30m && git push)
